=== Baresse/mapshup-charterng/examples/CnesXml.xsd
<xsd:schema targetNamespace="https://disastercharter.org/cgt" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml"
  elementFormDefault="qualified">
  <xsd:import id="gml" namespace="http://www.opengis.net/gml" schemaLocation="http://schemas.opengis.net/gml/3.1.1/base/gml.xsd" />
  <xsd:complexType xmlns="https://disastercharter.org/cgt" name="kmlUrlsType">
    <xsd:sequence>
      <xsd:element name="kmlUrl" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType xmlns="https://disastercharter.org/cgt" name="locationType">
    <xsd:sequence>
      <xsd:element ref="gml:Point" />
      <xsd:element ref="gml:Rectangle" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="kmlUrls" type="kmlUrlsType" />
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:element name="disaster">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="updated" type="xsd:string" />
        <xsd:element name="title" type="xsd:string" />
        <xsd:element name="date" type="xsd:string" />
        <xsd:element name="callid" type="xsd:string" />
        <xsd:element name="type" type="xsd:string" />
        <xsd:element name="description" type="xsd:string" />
        <xsd:element name="link" type="xsd:string" />
        <xsd:element name="image" type="xsd:string" />
        <xsd:element name="location" type="locationType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== Baresse/mapshup-charterng/examples/example-simple.xml
<?xml version="1.0" encoding="utf-8"?>
<disaster xmlns="https://disastercharter.org/cgt" 
xmlns:cgt="https://disastercharter.org/cgt"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:gml="http://www.opengis.net/gml"
xsi:schemaLocation="http://www.opengis.net/gml http://schemas.opengis.net/gml/3.1.1/base/gml.xsd cgt ./CnesXml.xsd" >
<updated>"2010-11-23T20:35:00+0000"</updated>
<title>Debris flow in China</title>
<date>2010-08-14T20:38:00+0000</date>
<callid>322</callid>
<type>OTHER</type>
<description>Sever rain in Wenchuan County, Sichuan Province has triggered many large debris flow in Yingxiu, Yingxiu township. At least 32 people are missing. Approximately 10,000 residents have been evacuated</description>
<link>https://intlcharter-prod.netcetera.ch/web/guest/activations/-/asset_publisher/y8Qb/content/act-123</link>
<image></image>
<location>
<gml:Point gml:id="p1" srsName="urn:ogc:def:crs:EPSG:6.6:4326">
<gml:pos  srsDimension="2">31.03 103.29</gml:pos>
</gml:Point>
</location>
</disaster>
